// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ovning_9.Data;

#nullable disable

namespace Ovning_9.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20260627073918_AddDataAnnotations")]
    partial class AddDataAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ovning_9.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Peripherals",
                            Count = 45,
                            Description = "Mechanical RGB keyboard",
                            Name = "Keyboard",
                            Orderdate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 899,
                            Shelf = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Displays",
                            Count = 12,
                            Description = "27 inch 4K IPS",
                            Name = "Monitor",
                            Orderdate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3499,
                            Shelf = "B3"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Peripherals",
                            Count = 60,
                            Description = "Ergonomic wireless mouse",
                            Name = "Mouse",
                            Orderdate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 549,
                            Shelf = "A2"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Audio",
                            Count = 25,
                            Description = "Noise cancelling USB headset",
                            Name = "Headset",
                            Orderdate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1299,
                            Shelf = "C1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
